# Generated by Django 6.0.5 on 2026-06-02 11:47

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_address_customuser_age_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(default=api.models.generate_tracking_id, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='customization_type',
            field=models.CharField(choices=[('text', 'Text'), ('photo', 'Photo')], max_length=10),
        ),
    ]
