# Generated by ChatGPT - adds wallet and referral code fields to CustomUser
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_order_created_at_alter_order_tracking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
