# Generated by Django 6.0.5 on 2026-06-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_walletwithdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customization_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
