# Generated by Django 6.0.5 on 2026-06-09 09:35

from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_orderitem_customization_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('mug', 'Mug'), ('tshirt', 'T-Shirt'), ('polo', 'Polo T-Shirt'), ('bottle', 'Bottle')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('birthday', 'Birthday'), ('love', 'Love & Anniversary'), ('family', 'Family & Parents'), ('friends', 'Friends'), ('cats', 'Cats & Pets'), ('general', 'General & Holiday'), ('motivational', 'Motivational'), ('custom', 'Custom / Other')], default='general', max_length=30)),
                ('image', models.ImageField(help_text='Upload the design wrap image', upload_to='designs/')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('239.00'), max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, default=Decimal('299.00'), max_digits=10)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product Design',
                'verbose_name_plural': 'Product Designs',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
