# Generated by Django 6.0.6 on 2026-06-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_productdesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='trending_image',
            field=models.ImageField(blank=True, help_text='High-quality image for the trending popup', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='trending_tagline',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
