# Generated by Django 6.0.6 on 2026-06-11 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_productreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="Custom name for this trending design (blank to use product's name)", max_length=100)),
                ('tagline', models.CharField(blank=True, help_text="Catchy tagline for this trending design (blank to use product's description)", max_length=255)),
                ('image', models.ImageField(help_text='Upload high-quality image for the trending blueprints display', upload_to='trending/')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trending_designs', to='api.product')),
            ],
            options={
                'verbose_name': 'Trending Design',
                'verbose_name_plural': 'Trending Designs',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
